import type { Task } from "./Types";

export const errorTask: Task[] = [
  {id: "1", title: "Errore", description: "Errore nel Caricare le Task", completed: false, dueDate: new Date(), priority: "high", tags: "work", createdAt: new Date()},
]



export const DummyTasks: Task[] = [
  {
    id: "1",
    title: "Setup development environment",
    description: "Install Node.js, VS Code, and configure the React project.",
    completed: true,
    dueDate: new Date("2025-01-15"),
    priority: "high",
    tags: "work",
    createdAt: new Date(),
    subtasks: [],
    attachments: [],
  },
  {
    id: "2",
    title: "Study React Hooks",
    description: "Deep dive into useState, useEffect, and useContext for the project.",
    completed: true,
    dueDate: new Date("2025-01-20"),
    priority: "medium",
    tags: "work",
    createdAt: new Date(),
    subtasks: [],
    attachments: [],
  },
  {
    id: "3",
    title: "Quarterly presentation",
    description: "Prepare slides for Q4 meeting with company stakeholders.",
    completed: false,
    dueDate: new Date("2025-01-30"),
    priority: "high",
    tags: "work",
    createdAt: new Date(),
    subtasks: [],
    attachments: [],
  },
  {
    id: "4",
    title: "Server data backup",
    description: "Perform a full production database backup.",
    completed: false,
    dueDate: new Date("2025-02-01"),
    priority: "high",
    tags: "work",
    createdAt: new Date(),
    subtasks: [],
    attachments: [],
  },
  {
    id: "5",
    title: "Implement dark mode",
    description: "Add dark theme to the TaskFlow application.",
    completed: false,
    dueDate: new Date("2025-08-15"),
    priority: "low",
    tags: "work",
    createdAt: new Date(),
    subtasks: [],
    attachments: [],
  },
  {
    id: "6",
    title: "Project code review",
    description: "Review team code and provide constructive feedback.",
    completed: false,
    dueDate: new Date("2025-08-10"),
    priority: "medium",
    tags: "work",
    createdAt: new Date(),
    subtasks: [],
    attachments: [],
  },
  {
    id: "7",
    title: "Dental check-up",
    description: "Book and attend routine dental check-up.",
    completed: false,
    dueDate: new Date("2025-08-20"),
    priority: "medium",
    tags: "personal",
    createdAt: new Date(),
    subtasks: [],
    attachments: [],
  },
  {
    id: "8",
    title: "Summer vacation 2025",
    description: "Plan and book vacation for August 2025.",
    completed: false,
    dueDate: new Date("2025-09-01"),
    priority: "low",
    tags: "personal",
    createdAt: new Date(),
    subtasks: [],
    attachments: [],
  },
  {
    id: "9",
    title: "Advanced TypeScript course",
    description: "Enroll in and complete an online TypeScript course for future projects.",
    completed: false,
    dueDate: new Date("2025-10-15"),
    priority: "medium",
    tags: "work",
    createdAt: new Date(),
    subtasks: [],
    attachments: [],
  },
  {
    id: "10",
    title: "Deploy app to production",
    description: "Set up CI/CD and deploy TaskFlow to production server.",
    completed: false,
    dueDate: new Date("2025-12-01"),
    priority: "high",
    tags: "work",
    createdAt: new Date(),
    subtasks: [],
    attachments: [],
  }
];
